# Site settings
title: Coupe Robots-JU
description: La coupe de robotique jurassienne à Delémont
url: "https://coupe.robots-ju.ch"

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->
permalink: /:year/:month/:day/:title
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      banner_image: /media/banners/blackboard.jpg
sass:
    style: compressed

exclude:
  - Gemfile
  - README.md

main_menu:
  - title: Accueil
    url: /
  - title: Programme
    url: /programme
  - title: Participer
    url: /equipes/participer
  - title: Résultats 2019
    url: /resultats/2019
  - title: Contact
    url: /contact

sitemap:
  visitors:
    - title: Accueil
      url: /
    - title: Programme
      url: /programme
    - title: Contact
      url: /contact
    - title: Sponsoring
      url: /sponsoring
    - title: Presse et logos
      url: /presse
    - title: Club Robots-JU
      url: https://robots-ju.ch/
  competitors:
    - title: Participer
      url: /equipes/participer
    - title: Règlement
      url: /equipes/reglement
    - title: Résultats 2019
      url: /resultats/2019
    - title: Résultats 2018
      url: /resultats/2018
    - title: Résultats 2017
      url: /resultats/2017
    - title: Résultats 2016
      url: /resultats/2016

social_links:
  - title: Twitter
    url: https://twitter.com/CoupeRobotsJU
    label: "@CoupeRobotsJU"
    icon: twitter
  - title: Facebook
    url: https://www.facebook.com/CoupeRobotsJU/
    label: "@CoupeRobotsJU"
    icon: facebook
  - title: YouTube
    url: https://www.youtube.com/@RobotsJU
    label: /robotsju
    icon: youtube-play
  - title: Flickr
    url: https://www.flickr.com/photos/robots-ju/
    label: "robots-ju"
    icon: flickr

concours:
    finance_inscription: 60
    finance_repas: 10
